### ISSUE TITLE
annoying cutoff warning goes to stdout

### ISSUE THREAD

**Issue by noambernstein** [libAtoms/QUIP#70]
It's pretty annoying that the "WARNING: Potential_calc: cutoff of Atoms object (-1.0000000000000000) < Potential cutoff (5.0000000000000000) - increasing it now" message goes to stdout.  Do we have a mechanism for switching it to stderr?

**Comment by jameskermode** [comment]
This comes from `print_warning()` from System.f95 - probably this should just be switched to write to stderr?

**Comment by noambernstein** [comment]
> On Jul 26, 2017, at 11:40 AM, James Kermode <notifications@github.com> wrote:
> 
> This comes from print_warning() from System.f95 - probably this should just be switched to write to stderr?
> 

I think that'd be helpful, yes.

  Noam

**Comment by jameskermode** [comment]
Done - I have hardcoded stderr as unit 0, as the correct way find the unit numbers via  `use instrinsic` seems to be a Fortran 2003 feature that may not yet be fully supported, but if anyone knows different please feel free to change.

**Comment by tdaff** [comment]
I think this is not properly fixed. Since it is calling write directly now, it ignores the verbosity and the mechanism to make sure the warning is only printed once no longer works (I think it does some manipulation of the verbosity), so the warning gets printed a very large number of times. This is especially apparent when using ase to do things.

I was also thinking that the `-1` case is a special one to indicate that no cutoff is set, so could skip the warning completely?

**Comment by jameskermode** [comment]
Ok, makes sense, let's just remove it altogether.

**Comment by sujona** [comment]
Hey, did you do anything about this? I pulled from 'public' and still get the message. Is there a way to change this -1 value from python instead?

**Comment by gabor1** [comment]
I've special cased -1.0 and 0.0.

But I disagree with writing to unit 0 / stderr. I think this is a completely legitimate scientific user message. I would expect stderr to get things like core dump messages, and kernel level stuff, not user output. 

with the exception as above, we'll get much fewer of these, can I redirect print_warning to go back to the standard log ? you can grep -v the WARNING if you don't want to see them

**Comment by noambernstein** [comment]
> On Mar 20, 2018, at 8:11 PM, gabor1 <notifications@github.com> wrote:
> 
> I've special cased -1.0 and 0.0.
> 
> But I disagree with writing to unit 0 / stderr. I think this is a completely legitimate scientific user message. I would expect stderr to get things like core dump messages, and kernel level stuff, not user output.
> 
> with the exception as above, we'll get much fewer of these, can I redirect print_warning to go back to the standard log ? you can grep -v the WARNING if you don't want to see them
> 

But many ways of running generate hundreds or thousands of these. Basically one per evaluation.  If it works, why the warning?

     Noam

**Comment by gabor1** [comment]
we do have a verbosity manipulator so that it should only be printed once. I want to try to work on that... the original idea was that if you didn't set the cutoff, you get a warning, because you probably forgot, and you should think about it. 

-- Gábor

**Comment by gabor1** [comment]
I guess the other reason was that if you set a small cutoff, called a potential, then called another potential that set a huge cutoff for itself, then you are saddled with that large cutoff for all subsequent connect calls, and you don't even know about it. 

-- Gábor

**Comment by gabor1** [comment]
Can I close this now?

**Comment by bernstei** [comment]
Yeah.
